version: "3.7"
services:
  db:
    container_name: "k19092-mysql"
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "my-secret-pw"
      MYSQL_DATABASE: "app-db"
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    ports:
      - "127.0.0.1:33060:3306"
